# Generated by Django 5.2 on 2025-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'patient'), ('DOCTOR', 'doctor')], default='PATIENT', max_length=10),
        ),
    ]
