# Generated by Django 5.2 on 2025-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
