# Generated by Django 5.2 on 2025-05-07 10:29

import django.core.validators
import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_doctor_years_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_comment', models.TextField()),
                ('summary_comment', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='patient_requests/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), main_app.models.validate_file_size])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='main_app.issue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='main_app_pa_status_20cdfa_idx'), models.Index(fields=['created_at'], name='main_app_pa_created_1fb492_idx')],
            },
        ),
    ]
