# Generated by Django 5.2 on 2025-05-07 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_patientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='main_app.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrequest',
            name='title',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
