# Generated by Django 5.2 on 2025-05-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_patientrequest_patient_patientrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='main_app.issue'),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='main_app.patient'),
        ),
    ]
