# Generated by Django 5.2 on 2025-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_patientrequest_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
